name: Deploy with Firebase Config
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Create Firebase Config
        env:
          API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
        run: |
          cat > firebase-config.js <<EOF
          const firebaseConfig = {
            apiKey: "$API_KEY",
            authDomain: "$AUTH_DOMAIN",
            databaseURL: "$DATABASE_URL",
            projectId: "$PROJECT_ID",
            storageBucket: "$STORAGE_BUCKET",
            messagingSenderId: "$MESSAGING_SENDER_ID",
            appId: "$APP_ID"
          };
          EOF
          mv firebase-config.js public/js/
      
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: './public'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}