name: Deploy with Firebase Secrets
on:
  push:
    branches: [ main ]  # Only trigger on main branch pushes

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'  # Cache npm dependencies for faster builds
      
      - name: Install dependencies
        run: npm ci  # Use ci for cleaner installs

      - name: Create Firebase config
        env:
          FIREBASE_API_KEY: ${{ secrets.apiKey }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.authDomain }}
          FIREBASE_PROJECT_ID: ${{ secrets.projectId }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.storageBucket }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.messagingSenderId }}
          FIREBASE_APP_ID: ${{ secrets.appId }}
        run: |
          mkdir -p src/config
          cat > src/config/firebase-config.js <<EOF
          export const firebaseConfig = {
            apiKey: "$FIREBASE_API_KEY",
            authDomain: "$FIREBASE_AUTH_DOMAIN",
            projectId: "$FIREBASE_PROJECT_ID",
            storageBucket: "$FIREBASE_STORAGE_BUCKET",
            messagingSenderId: "$FIREBASE_MESSAGING_SENDER_ID",
            appId: "$FIREBASE_APP_ID"
          };
          EOF

      - name: Build project
        run: npm run build

      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@v2
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
